johnmcfarlane/cnl

include/cnl/bits/fixed_point_type.h
- no need for fixed_point::operator bool()
- already seems to be a perfectly good one in base class
- fixed_point::operator Integer() made explicit
- otherwise if participates in operator overload resolution
=> tightening the conversion operators on level 3

include/cnl/auxiliary/boost.multiprecision.h, include/cnl/numeric.h, src/test/boost.multiprecision.cpp, src/test/index.cpp
=> Signed multiprecision used bits

src/test/CMakeLists.txt
switches googletest over to a version that works with latest VS2017 preview
- https://github.com/google/googletest/pull/1311
=> cmake fixes to work around gtest failure under 2017 preview

include/cnl/auxiliary/boost.multiprecision.h, include/cnl/auxiliary/boost.simd.h, include/cnl/bits/fixed_point/constants.h, include/cnl/bits/fixed_point/extras.h, include/cnl/bits/fixed_point/named.h, include/cnl/bits/fixed_point/operators.h, include/cnl/bits/fixed_point/type.h, include/cnl/bits/number_base.h, include/cnl/elastic_integer.h, include/cnl/num_traits.h, include/cnl/overflow_integer.h, include/cnl/precise_integer.h, src/benchmark/benchmark.cpp, src/test/CMakeLists.txt, src/test/boost.multiprecision.cpp, src/test/boost.simd.cpp, src/test/elastic/elastic_integer.cpp, src/test/fixed_point/constants.cpp, src/test/fixed_point/elastic/elastic_fixed_point.cpp, src/test/fixed_point/elastic/make_elastic_fixed_point.cpp, src/test/fixed_point/extras.cpp, src/test/fixed_point/fixed_point_common.h, src/test/fixed_point/fixed_point_math_common.h, src/test/fixed_point/overflow/fixed_point_throwing_integer.cpp, src/test/num_traits.cpp, src/test/overflow/elastic/safe_integer.cpp, src/test/overflow/overflow.cpp, src/test/overflow/overflow_integer.cpp, src/test/papers/p0675.cpp
removes code that puts onus on `fixed_point<>` to avoid overflow
- is the job of `elastic_integer`
- complicates design
- adds a second responsibility to `fixed_point<>`
- can't always succeed anyway
- addresses #88
=> Shift simplification

include/cnl/bits/fixed_point/extras.h, include/cnl/bits/fixed_point/math.h, include/cnl/bits/fixed_point/named.h, include/cnl/bits/fixed_point/num_traits.h, include/cnl/bits/fixed_point/operators.h, include/cnl/bits/fixed_point/type.h, include/cnl/bits/number_base.h, include/cnl/elastic_integer.h, include/cnl/num_traits.h, include/cnl/overflow.h, include/cnl/overflow_integer.h, include/cnl/rounding_integer.h, src/test/fixed_point/elastic/elastic_fixed_point.cpp, src/test/fixed_point/fixed_point_common.h, src/test/fixed_point/fixed_point_math_common.h, src/test/fixed_point/p0037.cpp, src/test/fixed_point/rounding_fixed_point.cpp, src/test/number_test.h, src/test/overflow/overflow_integer.cpp, src/test/papers/p0675.cpp, src/test/rounding/rounding_integer.cpp
- changes signature of cnl::from_rep
- second parameter moved to cnl::from_rep::operator()
=> removes _impl::from_rep

include/CMakeLists.txt
When I run "make install" with the previous CMakeLists.txt in the develop branch I get:
"""
Install the project...
-- Install configuration: ""
CMake Error at include/cmake_install.cmake:36 (file):
file INSTALL cannot find
"~/Projects/cnl/include/include/cnl".
Call Stack (most recent call first):
cmake_install.cmake:37 (include)
Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
"""
Based on the documentation (https://cmake.org/cmake/help/v3.0/command/install.html), it appears it should be  "cnl", not "include/cnl".  I'm running cmake version 3.5.1
=> Fix install path

README.md
Fix also spurious trailing spaces in the neighbourhood.
=> Fix typo in Khronos Group name

src/test/fixed_point/elastic/rounding/rounding_elastic_number.cpp
Right shift with 0 fails, thus the test. I believe it should work.
=> Testing shift with zero value

src/test/CMakeLists.txt, src/test/fixed_point/elastic/rounding/rounding_elastic_number.cpp
I'm still getting used to multiple remotes and I accidentally pushed to *hbe72/cnl/rounding_elastic_number* most of these changes already. This is the same branch rebased onto the fix in *develop*. Feel free to merge/replace/squash/revert as you see fit.
=> Rounding elastic number

include/cnl/bits/fixed_point/constants.h, include/cnl/numeric.h, src/test/fixed_point/constants.cpp, src/test/fixed_point/fractional_ctor.h, src/test/numeric.cpp
Move mathematical constants out of math_constants namespace
=> Math constants

include/cnl/auxiliary/boost.multiprecision.h, include/cnl/bits/fixed_point/constants.h, include/cnl/bits/fixed_point/fractional.h, include/cnl/bits/fixed_point/num_traits.h, include/cnl/bits/fixed_point/type.h, include/cnl/bits/rounding.h, include/cnl/bits/used_digits.h, include/cnl/elastic_integer.h, include/cnl/integral_constant.h, include/cnl/num_traits.h, include/cnl/numeric.h, include/cnl/overflow_integer.h, include/cnl/rounding_integer.h, include/cnl/static_number.h, src/test/CMakeLists.txt, src/test/elastic/elastic_integer.cpp, src/test/elastic/rounding/elastic_integer_rounding.cpp, src/test/elastic/rounding/overflow/rounding_safe_integer.cpp, src/test/fixed_point/elastic/rounding/rounding_elastic_number.cpp, src/test/fixed_point/fixed_point_common.h, src/test/num_traits.cpp, src/test/numeric.cpp, src/test/papers/p0675.cpp, src/test/vc.cpp
addresses test failure in #232 and towards #187
=> Move implementation of cnl::used_digits out of public API

include/cnl/_impl/fixed_point/extras.h, include/cnl/_impl/fixed_point/type.h
- move crib-specific functions out of type.h
- flattened namespaces
=> Quick clean-up of _impl::crib

.appveyor.yml
- they are prohibitively slow
- the last one was quite similar to the first
- the remaining two are now more diverse than before
=> Remove one of three appveyor builds

include/cnl/_impl/rounding/convert.h, src/test/CMakeLists.txt, src/test/_impl/rounding/convert.cpp
@hbe72 given how horrendous the SFINAE logic is in this version, the three-specialization version starts to look pretty good! Otherwise all looks good. Thanks
=> Added conversions and tests for cnl/_impl/rounding/convert.h

include/cnl/overflow_integer.h
- default-initialization isn't the concern of an integer type with
"overflow" in the name
- this is the same reason divide-by-zero isn't handled by this type
Addresses #240
=> Reinstate overflow_integer default constructor

.circleci/test.sh, include/cnl/_impl/fixed_point/extras.h, src/test/fixed_point/fixed_point_common.h, src/test/fixed_point/overflow/fixed_point_trapping_integer.cpp, src/test/overflow/overflow.cpp
- to help diagnose test failures during CI
=> log errors on circle-ci ctest failures

include/cnl/_impl/cmath/abs.h, src/test/fraction.cpp
- makes things slightly easier to reason about
- may turn out to be a bad idea, e.g.
cnl::abs((signed char)-128)
=> abs should return same type as input parameter

src/test/CMakeLists.txt, src/test/main.cpp
- includes cnl/all.h
- gives the linker the opportunity to identify ODR violations
- would have caught the issue addressed in 931de2
=> Reintroduce src/test/main.cpp

include/cnl/_impl/native_tag.h, include/cnl/_impl/overflow/native.h, include/cnl/_impl/overflow/saturated.h, include/cnl/_impl/overflow/throwing.h, include/cnl/_impl/overflow/trapping.h, include/cnl/_impl/overflow/undefined.h, include/cnl/_impl/tagged.h, include/cnl/overflow.h, include/cnl/overflow_integer.h, include/cnl/rounding.h, include/cnl/rounding_integer.h, src/test/_impl/rounding/tagged_convert_operator.cpp, src/test/elastic/rounding/elastic_integer_rounding.cpp, src/test/fixed_point/overflow/fixed_point_throwing_integer.cpp, src/test/overflow/elastic/safe_integer.cpp, src/test/overflow/overflow.cpp, src/test/rounding/fixed_point/elastic_integer/elastic_number.cpp, src/test/rounding/fixed_point/fixed_point.cpp, src/test/rounding/rounding.cpp, src/test/zero_cost_free_functions.cpp
Uniform free function API with `convert` restored to `cnl` namespace.
=> Free functions

README.md
A new link provided by JetBrains on renewal of OSS licence. Logo slightly larger.
=> Amend CLion link in README.md

include/cnl/_impl/native_tag.h, include/cnl/_impl/rounding.h, src/test/elastic/rounding/elastic_integer_rounding.cpp, src/test/rounding/rounding.cpp
right-shift no longer rounds to nearest with `nearest_rounding_tag`. Resolves #418
=> Right-shift rounding

src/test/CMakeLists.txt
- fixes warning from GCC 9: deprecated-copy
=> Advance gtest revision

.idea/codeStyles/codeStyleConfig.xml, include/cnl/_impl/fixed_point/named.h, include/cnl/_impl/fixed_point/type.h, include/cnl/_impl/num_traits/from_value.h, include/cnl/_impl/number_base.h, include/cnl/_impl/overflow/is_overflow.h, include/cnl/elastic_integer.h, include/cnl/elastic_number.h, src/test/_impl/wide_integer/from_value.cpp, src/test/_impl/wide_integer/literals.cpp, src/test/_impl/wide_integer/operators.cpp, src/test/elastic/elastic_integer.cpp, src/test/fixed_point/decimal.cpp, src/test/fixed_point/fixed_point_common.h, src/test/integer/from_value.cpp, src/test/num_traits.cpp, src/test/overflow/overflow_integer.cpp, src/test/rounding/rounding_integer.cpp, src/test/vc.cpp
* Renames `from_number` to `from_value`.
* Fixes compiler errors/slowdowns when using latest GCC6 that comes with latest Ubuntu.
* Minor fixes to *elastic_integer.h*.
=> Ubuntu 19.04 assortment

README.md
Minimum Clang version is now 3.8 due to N3922
- CMake (optional) is now only tested on 3.7.2 and above.
=> Increase minimum software requirements in README

include/cnl/constant.h
- S is a scalar
- value must match
- add default ctor by necessity
=> Add constant::constant(S)

src/test/CMakeLists.txt, src/test/all.cpp, src/test/common.cpp
- using gtest_main instead
- no longer serves a useful purpose
- tests are currently not being linked
=> Remove TestMain target

.travis/test-osx.sh
- perhaps as a result of moves away from Python 2.x
- solution came as part of a brew error message
- but not before following suggestion here:
https://stackoverflow.com/questions/13354207/how-to-symlink-python-in-homebrew/13354417#13354417
=> Fix to another out-of-nowhere OS X Brew failure

.travis.yml
- move further up, giving them more time to complete
- the last one is frequently the bottleneck to completion
- ordered more consistently WRT linux builds and compiler versions
- added comment so I can remember what version of Clang++ OS X is using
by default
=> Rearranged OS X Travis builds

test/unit/CMakeLists.txt
- resulting in bogus header search path ending in 'SYSTEM'
=> Fix abuse of SYSTEM CMake keyword

.appveyor.yml
- CNL_STD was removed previously
- CMAKE_CXX_STANDARD does the job now
=> Fix broken CMake config param in AppVeyor builds

test/scripts/bits/config.sh
`CMAKE_PROJECT_INCLUDE` instead of `CMAKE_PROJECT_cnl_INCLUDE` as this is a single-project repo.
=> Use simpler variable for hooking CMake->Conan

test/scripts/bits/config.sh
Both Conan and CMake default build type is _Release_ already.
No need to re-specify the defaults here.
=> Remove superfluous config flags

include/cnl/elastic_fixed_point.h
It's already defined in elastic_scaled_integer.h
which leads to compiler error when cnl/all.h is included
and the UDL is referenced.
=> Remove duplicate UDL from elastic_fixed_point.h

include/cnl/_impl/rounding.h, include/cnl/_impl/rounding/tie_to_pos_inf_rounding_tag.h, test/unit/rounding/rounding.cpp
Found the missing division to tie_to_pos_inf_rounding, thus the tie value is rounded towards positive infinity. Otherwise to nearest. Possibly better algorithms exists.
=> Adds the missing division to tie_to_pos_inf_rounding

.travis.yml
- In reality, we want deployment only from the main branch, but
- Travis-CI treats tags as branches
when they are used to trigger a build.
=> Allow deployment to happen from any branch

include/cnl/constant.h
Recent versions apparently address the bug being worked around.
The version for which the fix is applied is unclear.
Please report if it doesn't work for you, stating which version
of MSVC and what the compiler error is.
https://github.com/johnmcfarlane/cnl/pull/637#discussion_r474010828
=> Adjust MSVC workaround for recent versions

.circleci/config.yml
GCC head appears not to work with GTest 1.10.0:
In file included from /root/project/googletest/googletest/src/gtest-all.cc:42:
/root/project/googletest/googletest/src/gtest-death-test.cc: In function 'bool testing::internal::StackGrowsDown()':
/root/project/googletest/googletest/src/gtest-death-test.cc:1301:24: error: 'dummy' may be used uninitialized [-Werror=maybe-uninitialized]
1301 |   StackLowerThanAddress(&dummy, &result);
|   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
https://app.circleci.com/pipelines/github/johnmcfarlane/cnl/545/workflows/b2c40722-d238-436d-baeb-b12fdd9601f0/jobs/9448
=> Bump gtest to current head in cmake-test-gcc Circle CI job

.github/deploy.sh, .github/workflows/deploy.yml, .github/workflows/test.yml
.github/deploy.yml wasn't using CNL_VERSION when running doc/generage.sh,
which wasn't correctly parsed anyway. Now doc/generate.sh is invoked from
.github/deploy.sh with correct value for CNL_VERSION.
Result is that documentation published to johnmcfarlane.github.io/cnl/ has
correct version extracted from Git tag -- rather than fallback label,
"development".
=> Fix Doxygen deployment version

.github/workflows/test.yml, CMakeLists.txt, README.md, include/cnl/_impl/config.h
* Removes CI support for C++11/14/17
* Requires C++20 compiler support in CMake
* Directs readers of README.md to _v1.x_ branch for legacy support.
* Removes preprocessor language check.
=> C++20 drop C++17

include/cnl/_impl/fraction/operators.h, test/unit/fraction/fraction.cpp
- replaces naive operator<< which printed char-sized integers
as chars, not numbers
=> Use to_string for operator<< w. fraction

.github/deploy, .gitmodules, doc/generate
In !715, there was a failed attempt to remove all of the bulk of the gh-pages branch by force-pushing back to its initial node. However, that retroactively breaks most/all commits in the main/v1.x branches back to their initial node because they all contain a submodule reference to some commit in gh-pages. So those cannot easily be deleted now.
The compromise is the remove all commits which do not yet feature in a doc/gh-pages submodule reference and change the script so it doesn't add fresh new Doxygen content, but instead replaces the previous head of gh-pages. The submodule reference is also removed as it serves no purpose other than to make the content of /doc slightly more confusing.
=> Remove gh-pages submodule

include/cnl/_impl/scaled_integer/to_chars.h
Latest MSVC (16.8) gives big compile error explosion on this, without the added parenthesis it seems to be treating the < as part of the type/template rather than a less than.
=> v1.x: Fix compilation of enable_if_t for scaled_integer/to_chars.h

include/cnl/_impl/wrapper/set_tag.h
- would only have been working for wrapper<Rep, native_tag> previously
=> Add missing input tag to set_tag<wrapper<...>>

include/cnl/_impl/elastic_integer/custom_operator.h, test/unit/elastic_integer/elastic_integer.cpp
- was not converting unsigned types to signed
- design was non-symetrical,
- didn't acknowledge the fact that + is a sign
=> Fix signedness for elastic_integer unary +

conanfile.py
- This makes the default explicit.
- It's purely so I can remember where to flip the switch.
=> Set cmake.verbose=False in conanfile.py

.clang-tidy, include/cnl/_impl/scaled_integer/to_chars.h, include/cnl/_impl/to_chars.h
- readability-avoid-const-params-in-decls complains about 'declarations'
which are patently definitions
=> Disable flaky Clang-Tidy check

include/cnl/_impl/cnl_assert.h, include/cnl/_impl/unreachable.h
- CNL_ASSUME tied to _impl::unreachable
- condition of CNL_ASSUME no evaluated in default case (non-GCC/Clang/MSVC)
- unreachable("message") invocation allowed
=> Fixes to _impl::unreachable & CNL_ASSUME

include/cnl/_impl/scaled_integer/to_chars.h, include/cnl/_impl/scaled_integer/to_string.h, include/cnl/elastic_scaled_integer.h, test/unit/scaled_integer/elastic/elastic_scaled_integer.cpp, test/unit/scaled_integer/to_chars.h
- to_string of scaled_integer now takes non-binary radixes
- mainly, this means calculating the correct maximum width of a number
once it's converted to decimal
- generalising this to all bases is not fun
- added test of
- UDLs involving thousandths
- some mildly ugly-ass UDLs being converted back into decimal in strings
=> Fix support for streaming decimal scaled_integer

README.md, test/toolchain/clang-libc++.cmake, test/toolchain/clang.cmake, test/toolchain/gcc-armv7.cmake, test/toolchain/gcc.cmake, test/unit/_impl/wide_integer/generic.cpp, test/unit/_impl/wide_integer/literals.cpp, test/unit/static_integer/operators.cpp, test/unit/static_integer/shift_left.cpp
- require much compile-time evaluation
=> Guard tests that often fail to compile

test/toolchain/gcc.cmake
- also _GLIBCXX_DEBUG_PEDANTIC
- enables run-time checking of some libstdc++ contracts
=> Define `LIBCXX_DEBUG` for GCC toolchain

.clang-tidy, .github/settings.yml, .github/workflows/test.yml, include/cnl/_impl/custom_operator/homogeneous_operator_tag_base.h, include/cnl/_impl/custom_operator/overloads.h, include/cnl/_impl/duplex_integer/definition.h, include/cnl/_impl/num_traits/fixed_width_scale.h, include/cnl/_impl/num_traits/set_digits.h, include/cnl/_impl/num_traits/unwrap.h, include/cnl/_impl/overflow/is_overflow.h, include/cnl/_impl/overflow/is_overflow_tag.h, include/cnl/_impl/power_value.h, include/cnl/_impl/rounding/is_rounding_tag.h, include/cnl/_impl/wide_tag/is_wide_tag.h, test/unit/scaled_int/scaled_int_common.h, test/unit/static_number/operators.cpp
- make -head images more prominent
- clang-head-analyse
- uses Clang-14 pre-release
- used to Clang-Tidy/sanitizers in Conan job
- gcc-head
- uses GCC-12 pre-release
- sanitizers enabled by default in Conan jobs
- CMake jobs just use clang-13 and gcc-11
- clang-format upgraded to clang-13
=> CI job shuffle

.github/conan/profiles/linux-gcc-head, test/toolchain/gcc-head.cmake
90% certain this warning is bogus. [GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88443). [creduced repro](https://godbolt.org/z/h7fsqacfd)
=> Disable bogus warnings in latest GCC

conanfile.py
- in hopes of avoiding CI job failures caused by slow JFrog REST API.
- example failure:
- job:
https://github.com/johnmcfarlane/cnl/runs/4427931463?check_suite_focus=true#step:7:51
- message:
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/conans/search?q=boost%2F%2A&ignorecase=False (Caused by ReadTimeoutError("HTTPSConnectionPool(host='center.conan.io', port=443): Read timed out. (read timeout=60.0)"))
- GitHub issue:
https://github.com/conan-io/conan-center-index/issues/950
- JFrog issue:
https://www.jfrog.com/jira/browse/RTFACT-26310
=> Clamp Boost version

.github/break-it
- perform all the refactoring first
- put all the results second
- makes resolving conflicts smoother
=> Split break-it script in two

conanfile.py
- only specify minimum
- likely not to bump to 2.x for a long time
- and might not even be a problem then
=> Broaden version ranges of dependencies

.github/workflows/pr.yml, .github/workflows/push.yml
Some runs appear to be stuck with an empty cache. Cache could have been
generated before certain fixes were applied.
=> bump cache slug

.github/workflows/push.yml, CONTRIBUTING.md
Now with ccache action merged, Conan cache is maybe no longer used in main branch builds. So I'm reinstating the more complex key rules for the cache (not ccache!) action.
=> ref_name in cache slug

.github/workflows/wide-integer.yml
- Run daily to remind if update is available.
- Isn't otherwise helpful during PR process.
- Config taken from wide-integer project.
=> Remove wide-integer check from CI

include/cnl/_impl/scaled_integer/num_traits.h, include/cnl/_impl/scaled_integer/to_chars_capacity.h
- Only true when Radis is binary (2)
- Add test of to_chars_static of elastic_scaled_integer
=> Fix incorrect use of exponent as fractional digits

test/unit/presentations/cppcon2017.cpp, test/unit/presentations/cppdub2018.cpp
Two tests won't compile when done so with g++12 because of an old workaround added for MSVC. I've extended it to include g++ and just plucked out the __cpluscplus version string from my locally installed filesystem include file.
=> Fixed redefinition error when compiling with g++12
