include/cnl/bits/fixed_point_constants.h, include/cnl/numeric.h, src/test/fixed_point/fixed_point_constants.cpp, src/test/numeric.cpp
for `float`, `double`, `long double` and `fixed_point`
=> updated set of math constants

.travis.yml
It sounds like there are 2 cores. Not sure if they are hyper-threaded. Starting off with 4 jobs...
https://docs.travis-ci.com/user/speeding-up-the-build/#Makefile-parallelization-example
=> make -j 4 ... doh!

.travis.yml
- hope is that OS X jobs get queued earlier
without holding up Linux builds
=> disperses OS X Travis builds through matrix

.travis.yml
- don't wait for OS X builds to finish before passing the build
1. https://github.com/travis-ci/travis-ci/issues/8552
=> speculative fix for travis osx issue.

src/test/CMakeLists.txt
- also exceptions to warnings were not represented properly
=> oops: forgot to add cppcon2017.cpp to test target

include/cnl/bits/fixed_point_extras.h, include/cnl/bits/fixed_point_named.h, src/test/fixed_point/fixed_point_common.h, src/test/fixed_point/p0037.cpp
Remove `cnl::add` and `cnl::subtract` for `cnl::fixed_point`
=> Remove cnl::add/subtract for fixed_point

include/cnl/integral_constant.h
=> temporarily re-adding integral_constant.h

src/test/CMakeLists.txt
avoids warning in MSVS 2015 Preview
=> updates gtest SHA

doc/Doxyfile, include/cnl/bits/encompasses.h, include/cnl/bits/fixed_point/operators.h, include/cnl/num_traits.h, include/cnl/overflow.h, src/test/CMakeLists.txt, src/test/elastic/elastic_integer.cpp, src/test/encompasses.cpp, src/test/fixed_point/fixed_point_common.h, src/test/safe/safe_integer.cpp
moves cnl/bits/fixed_point_*.h into cnl/bits/fixed_point/*.h
=> Assignment operators

include/cnl/bit.h, src/test/bit.cpp
- http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0556r1.html
=> implements P0556R1

include/cnl/elastic_integer.h, src/test/elastic/elastic_integer.cpp
=> Elastic make

include/cnl/bits/fixed_point/extras.h, src/test/fixed_point/elastic/elastic_fixed_point.cpp, src/test/fixed_point/extras.cpp
=> Elastic sqrt

src/test/papers/p0675.cpp
- no longer derived from _impl::number_base
- no longer in `cnl` namespace
=> makes `smart_integer` example type from P0675 cnl::_impl-independent

include/cnl/bits/config.h, include/cnl/bits/fixed_point/type.h, include/cnl/bits/number_base.h, include/cnl/overflow.h, src/test/zero_cost_average.cpp
=> Relaxed constexpr

doc/Doxyfile.in, include/cnl/bits/fixed_point/named.h, include/cnl/bits/fixed_point/num_traits.h, include/cnl/bits/fixed_point/type.h, src/test/fixed_point/fixed_point_common.h
=> fixed_point divide fixups

include/cnl/bits/fixed_point/type.h, include/cnl/bits/number_base.h
=> protects/removes various members of _impl::number_base

include/cnl/bit.h
=> removes seemingly unnecessary rotate fn checks

src/test/number_test.h, src/test/overflow/elastic/safe_integer.cpp
=> remove some #if conditionals from tests

include/cnl/auxiliary/boost.multiprecision.h, include/cnl/bits/fixed_point/extras.h, include/cnl/bits/terminate.h, include/cnl/elastic_integer.h, include/cnl/overflow.h, src/test/elastic/elastic_integer.cpp, src/test/fixed_point/fixed_point_common.h
=> Sqrt fixes

include/cnl/auxiliary/boost.multiprecision.h, include/cnl/bits/fixed_point/extras.h, include/cnl/bits/fixed_point/type.h, include/cnl/num_traits.h, src/test/boost.multiprecision.cpp, src/test/number_test.h
Fixes issues arising from #226
=> Sqrt multiprecision

include/cnl/bits/fixed_point/math.h, include/cnl/bits/fixed_point/type.h, include/cnl/bits/static_integer.h
- apparently, this improves compile times
=> Move SFINAE to function return types where possible

include/cnl/bits/fixed_point/constants.h, include/cnl/bits/fixed_point/operators.h, include/cnl/bits/fixed_point/type.h, include/cnl/elastic_integer.h, include/cnl/num_traits.h, include/cnl/numeric.h, src/test/elastic/elastic_integer.cpp, src/test/num_traits.cpp, src/test/numeric.cpp, src/test/overflow/overflow_integer.cpp, src/test/static_integer.cpp
- default to whatever is the radix of the Rep type
=> Change default for fixed_point Radix parameter

include/cnl/bits/fixed_point/extras.h, include/cnl/bits/fixed_point/math.h, include/cnl/bits/fixed_point/num_traits.h, include/cnl/bits/power.h, src/test/fixed_point/elastic/elastic_number.cpp, src/test/fixed_point/extras.cpp, src/test/fixed_point/fixed_point_math_common.h
=> Left shift db

include/cnl/bits/operators.h, include/cnl/overflow.h, src/test/limits.cpp, src/test/overflow/overflow.cpp, src/test/static_number.cpp
=> most negative number

include/cnl/bits/native_tag.h, include/cnl/bits/rounding.h, include/cnl/bits/throw_exception.h, include/cnl/overflow.h, include/cnl/overflow_integer.h, include/cnl/rounding_integer.h, src/test/fixed_point/overflow/fixed_point_trapping_integer.cpp, src/test/overflow/elastic/safe_integer.cpp, src/test/overflow/overflow.cpp, src/test/overflow/overflow_integer.cpp, src/test/rounding/rounding.cpp, src/test/rounding/rounding_integer.cpp, src/test/static_integer.cpp, src/test/static_number.cpp
=> Increment decrement overflow

include/cnl/bits/fixed_point/extras.h, src/test/fixed_point/elastic/elastic_number.cpp, src/test/fixed_point/extras.cpp
=> Fix abs compare zero

.travis.yml
- for GCC6 builds which are failing
=> Fix Travis CI build by changing xcode version

.appveyor.yml, include/cnl/_impl/fixed_point/constants.h, include/cnl/_impl/num_traits/digits.h, include/cnl/_impl/num_traits/is_composite.h, src/common/common.cmake, src/test/fixed_point/constants.cpp, src/test/numeric.cpp, src/test/presentations/cppcon2017.cpp, src/test/presentations/cppdub2018.cpp, src/test/readme.cpp
=> MSVC C++17 support

include/cnl/cstdint.h, src/test/cstdint.cpp
=> Fix negative values in CNL_INTMAX_C

include/cnl/_impl/duplex_integer/type.h, src/test/_impl/duplex_integer/type.cpp
- when converting signed negative duplex_integer to narrower integer
=> Fix bogus overflow trap related to negative values

.travis-setup-linux.sh, .travis.yml
Print lines of code in Travis-CI jobs
=> lines of code

.idea/codeStyles/codeStyleConfig.xml, include/cnl/_impl/fixed_point/named.h, include/cnl/_impl/fixed_point/type.h, include/cnl/_impl/num_traits/from_value.h, include/cnl/_impl/number_base.h, src/test/_impl/wide_integer/from_value.cpp, src/test/elastic/elastic_integer.cpp, src/test/fixed_point/decimal.cpp, src/test/fixed_point/fixed_point_common.h, src/test/integer/from_value.cpp, src/test/num_traits.cpp, src/test/overflow/overflow_integer.cpp, src/test/rounding/rounding_integer.cpp, src/test/vc.cpp
Rename `cnl::_impl::make_number` to `cnl::_impl::from_number`.
Addresses #392
=> make_number

src/test/CMakeLists.txt
- using personal fork
- the old upstream repo went away
=> Change Boost.SIMD repo

.travis.yml
- this build is timing out and complaining that xcode8 is too old
=> Change xcode8 Travis-CI image to xcode10.2

src/test/CMakeLists.txt, src/test/fixed_point/elastic/rounding/overflow/426.cpp, src/test/static_number/426.cpp
- https://github.com/johnmcfarlane/cnl/issues/426
- affirmation of results in fixed_point/elastic/rounding/overflow/426.cpp
- suggested alternative in static_number/426.cpp
=> Add tests of issue #426

include/cnl/_impl/to_chars.h
=> Remove floating-point value from to_chars

.appveyor.yml, include/cnl/_impl/num_traits/digits.h, include/cnl/_impl/num_traits/is_composite.h, include/cnl/_impl/type_traits/is_integral.h, include/cnl/_impl/wide_integer/literals.h, include/cnl/type_traits.h, src/common/common.cmake, src/test/CMakeLists.txt, src/test/_impl/wide_integer/literals.cpp, src/test/papers/p0037.cpp, src/test/papers/p0827.cpp, src/test/papers/p1050.cpp, src/test/presentations/cppcon2017.cpp, src/test/presentations/cppdub2018.cpp
=> Add -Wundef to tests

src/single_header/CMakeLists.txt
- was deleting docs folder half way though creating files
=> Fix dependencies for single-header targets

.travis.yml
- that looks like it'll never be fixed
=> Ditching GCC-5 on OS X due to assembler output bug

include/cnl/_impl/config.h
=> Add check for language version

conanfile.py
I created a simple Conan recipe for cnl. Example usage, from root of cnl repository: `conan create . cnl/0.0.1@bloomlife/testing`. 
If cnl starts using GitHub releases with version numbers we can do something fancier.
=> Conan Recipe

include/cnl/_impl/native_tag.h
- confusing when it's wrong
- causes CNL to exhibit UB due to the ___
=> Remove CNL_ERROR___cannot_use

CMakeLists.txt, README.md, src/single_header/CMakeLists.txt
=> Drop CMake version

src/test/_impl/duplex_integer/type.cpp
- not sure why they started occurring
=> Fix mysterious compiler errors

include/cnl/_impl/fraction/make_fraction.h
=> Rename variables, near and far

src/test/CMakeLists.txt
- fixes unit tests which are not currently being run in develop!
=> Swap link order of TestMain and unit test libs

.travis.yml, .travis/test-osx.sh
- speeds up installation of GCC
- aims to solve issue experienced by @hbe72 in #526.
=> Install Xcode CL tools

.vscode/settings.json, .vscode/tasks.json
- task to invoke the main test script
- CMake configuration parameters
=> Add some Visual Studio Code config

.travis.yml, README.md
- parser has issues that no other supported compilers have
=> Drop Clang 3.x

.appveyor.yml, .circleci/test-arm.sh, .travis/test.sh, README.md, test/CMakeLists.txt, test/benchmark/CMakeLists.txt, test/benchmark/review.py, test/unit/CMakeLists.txt
Replace Benchmark executable with test-benchmark test
=> Test benchmark

.appveyor.yml, include/cnl/_impl/overflow/is_overflow.h, test/unit/overflow/overflow.cpp
=> Change 1/2 of AppVeyor jobs to newer MSVC

.circleci/test-arm.sh, .travis.yml
=> Fix image use

.appveyor.yml, README.md, conanfile.py, test/scripts/bits/config.sh, test/scripts/unit-test.sh, test/unit/CMakeLists.txt
from `cmake_find_package` to `cmake_paths`
=> Switch Conan generators, again

.appveyor.yml, .circleci/config.yml, .circleci/test-arm.sh, .vscode/settings.json, CMakeLists.txt, README.md, test/CMakeLists.txt, test/benchmark/CMakeLists.txt, test/scripts/bits/config.sh, test/unit/CMakeLists.txt
=> Remove CNL_DEV

.circleci/config.yml
=> Hard-code circle-ci job CPUs

.circleci/config.yml
- otherwise jobs aren't deterministic
=> Peg gtest to latest release got circle-ci ctest job

include/cnl/_impl/scaled_integer/declaration.h, include/cnl/_impl/scaled_integer/type.h
=> Overflow disclaimer

conanfile.py
As advised here:
https://github.com/conan-io/conan/issues/7039#issuecomment-634979163
=> Fix overspecified Conan dependency

include/cnl/_impl/duplex_integer/multiply.h, include/cnl/_impl/fraction/make_fraction.h, test/cmake/toolchain/clang.cmake, test/cmake/toolchain/gcc-armv7-a.cmake, test/cmake/toolchain/gcc.cmake
#619 Investigating whether CNL fails when -Wshadow is enabled.
=> Add -Wshadow to GCC config

README.md, include/cnl/_impl/duplex_integer/divide.h, include/cnl/_impl/math_20.h, include/cnl/all.h
- CNL main branch renamed to main
- permalink into Linux repo
- relative path to in-repo file
=> Replace mentions of master branch

.vscode/settings.json, README.md
- Trying to make it a little easier to setup and run tests with Conan.
- Still tough though.
=> Revised README and VSCode config

.travis.yml, .travis/test-osx.sh
- Travis advises against this:
https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
=> Don't update brew packages

include/cnl/_impl/rounding.h, include/cnl/_impl/rounding/convert_operator.h, include/cnl/_impl/rounding/neg_inf_rounding_tag.h, include/cnl/_impl/scaled_integer/convert_operator.h, test/unit/CMakeLists.txt, test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point.cpp, test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point_nearest.cpp, test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point_neg_inf.cpp, test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point_tie_to_pos_inf.cpp
Introduces neg_inf_rounding_tag and improves tie_to_pos_inf testing.
=> Add neg inf rounding

test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point.cpp, test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point_nearest.cpp, test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point_neg_inf.cpp, test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point_tie_to_pos_inf.cpp
Changes according to the discussion
=> Clarifications to the elastic fixed point testing code

include/cnl/_impl/elastic_integer/is_number.h, include/cnl/_impl/number/binary_operator.h, include/cnl/_impl/number/comparison_operator.h, include/cnl/_impl/number/definition.h, include/cnl/_impl/number/from_value.h, include/cnl/_impl/number/inc_dec_operator.h, include/cnl/_impl/number/is_composite.h, include/cnl/_impl/number/is_number.h, include/cnl/_impl/number/operator_helpers.h, include/cnl/_impl/number/rounding.h, include/cnl/_impl/number/set_rep.h, include/cnl/_impl/number/set_rounding.h, include/cnl/_impl/number/shift_operator.h, include/cnl/_impl/number/to_rep.h, include/cnl/_impl/scaled_integer/is_number.h, include/cnl/overflow_integer.h, include/cnl/rounding_integer.h, test/unit/elastic_integer/elastic_integer.cpp, test/unit/elastic_integer/rounding_integer/rounding_elastic_integer.cpp, test/unit/integer/operators.cpp, test/unit/rounding/rounding_integer.cpp
Convert `is_number` from `struct` to `bool`.
=> is_number variable

include/cnl/_impl/fraction/hash.h, include/cnl/_impl/num_traits/from_rep.h, include/cnl/_impl/num_traits/from_value.h, include/cnl/_impl/num_traits/max_digits.h, include/cnl/_impl/num_traits/rounding.h, include/cnl/_impl/num_traits/scale.h, include/cnl/_impl/num_traits/set_digits.h, include/cnl/_impl/num_traits/to_rep.h, include/cnl/_impl/operators/native_tag.h, include/cnl/_impl/overflow/builtin_overflow.h, include/cnl/_impl/type_traits/add_signedness.h, include/cnl/_impl/type_traits/is_integral.h, include/cnl/_impl/type_traits/remove_signedness.h, include/cnl/type_traits.h
- remove struct, is_integral
- remove variable, is_integral_v
- add variable, is_integral
=> Add _impl::integral concept

include/cnl/_impl/wide_integer/literals.h, test/unit/papers/p0827.cpp
=> Fix copy/paste error in diagnostic message

doc/Doxyfile, include/cnl/_impl/scaled_integer/extras.h
=> Workaround bogus Doxygen error in extras.h

.github/workflows/test.yml, include/cnl/_impl/scaled_integer/numbers.h, test/unit/scaled_integer/fraction_ctor.h, test/unit/scaled_integer/numbers.cpp
=> Make <numbers> optional

include/cnl/_impl/duplex_integer/to_chars.h, include/cnl/_impl/scaled_integer/to_chars.h, include/cnl/_impl/to_chars.h
=> Replace cnl::to_chars_result

include/cnl/_impl/duplex_integer/multiply.h, test/unit/_impl/duplex_integer/operators.cpp
- multiplication with high bits set would drop upper bits
=> Fix another error in duplex_integer multiply

include/cnl/auxiliary/boost.multiprecision.h, test/unit/CMakeLists.txt, test/unit/boost.multiprecision.cpp
=> Fix broken Boost integration

test/toolchain/clang-libc++.cmake, test/toolchain/clang.cmake, test/toolchain/gcc-armv7.cmake, test/toolchain/gcc.cmake
- Clang and GCC via toolchain files
=> Add colour to compiler diagnostics

.github/workflows/test.yml, conanfile.py, include/cnl/_impl/fraction/hash.h, include/cnl/_impl/num_traits/to_rep.h, include/cnl/_impl/operators/native_tag.h, include/cnl/_impl/overflow/builtin_overflow.h, include/cnl/_impl/type_traits/is_integral.h, include/cnl/integer.h, test/unit/CMakeLists.txt, test/unit/cmath.cpp, test/unit/fixed_point.cpp, test/unit/integer.cpp
=> int128 satisfies fixed_point concept

include/cnl/_impl/ostream.h, include/cnl/_impl/wrapper.h, include/cnl/_impl/wrapper/ostream.h, include/cnl/_impl/wrapper/shift_operator.h, test/unit/overflow/overflow_integer.cpp
=> Fix missing operator<<(ostream, int128)

.github/workflows/test.yml, test/toolchain/clang-libc++.cmake, test/toolchain/clang.cmake, test/toolchain/gcc-armv7.cmake, test/toolchain/gcc.cmake
- in Conan Linux jobs
- ccache and Conan dependencies
=> Cache files in Conan linux builds

conanfile.py
- for reasons explained in the comment
=> Don't run benchmarks with CTest

include/cnl/_impl/elastic_tag/policy.h, test/unit/elastic_integer/elastic_integer.cpp
- result of X % Y cannot be wider than either of X or Y
=> Narrower result from elastic_integer modulo

include/cnl/elastic_scaled_integer.h, test/unit/_impl/rounding/convert_operator.cpp, test/unit/index.cpp, test/unit/papers/p0554.cpp, test/unit/rounding/scaled_integer/elastic_integer/elastic_scaled_integer.cpp, test/unit/rounding/scaled_integer/elastic_integer/elastic_scaled_integer_nearest.cpp, test/unit/rounding/scaled_integer/elastic_integer/elastic_scaled_integer_neg_inf.cpp, test/unit/rounding/scaled_integer/elastic_integer/elastic_scaled_integer_tie_to_pos_inf.cpp, test/unit/scaled_integer/elastic/elastic_scaled_integer.cpp, test/unit/scaled_integer/elastic/make_elastic_scaled_integer.cpp, test/unit/snippets.cpp, test/unit/zero_cost_average.cpp, test/unit/zero_cost_square.cpp
- change 2nd parameter from Exponent to Scale
=> Change API of elastic_scaled_integer

include/cnl/_impl/charconv/descale.h, test/unit/scaled_integer/to_chars.h
=> Fix infinite loop/incorrect output in descale

include/cnl/static_number.h
- use integer concept
- default to int
=> Uniform Narrowest parameter in static_number

README.md
One person used this ever and then I failed to notice. :(
=> Remove Gitter link

include/cnl/cmath.h, test/unit/cmath.cpp
=> Fix ambiguous overload error

README.md
Mostly so I don't have to set up CE from scratch each time!
=> Add Compiler Explorer link to README.md

.github/break-it
- rebases all 8 break-it_ branches to test a branch's CI
=> Add script break-it

test/unit/boost.throw_exception.h
- to macro definitions/attribute changes
=> Make boost.throw_exception.h more robust

.github/workflows/test.yml, doc/Doxyfile
Doxyfile is now auto-generated
- by `doxygen -s -u doc/Doxyfile` command
- job tests that it hasn't been altered by human hands
=> Doxyfile update

.github/conan/settings.yml, conanfile.py
=> Require Conan 1.43

.github/workflows/pr.yml, .github/workflows/push.yml
- lean: branch push
- heavy: pull request
=> Divide workflow in two

include/cnl/_impl/wrapper/definition.h
=> Remove instance of protected
